### ISSUE TITLE
Some ores missing after mining?

### ISSUE THREAD

**Issue by Murrlin** [WillR27/Blocklings#10]
When mining Redstone, Diamond, and Coal, the drops are missing from its inventory for some reason? In survival mode, with a diamond pick equipped...
Are what the blockling's abilities are, important?
For 1.12.2

**Comment by Murrlin** [comment]
Wait... I have Auto-smelt abilities on. Is that the culprit??

**Comment by WillR27** [comment]
Ohhhhhh that might be it, but it shouldn't delete the other ores haha. I will take a look, thanks.

**Comment by WillR27** [comment]
This will be fixed in 6.0.2 :)
