### ISSUE TITLE
SpongeForge Server - Fatal error when opening Inventory from Blockling

### ISSUE THREAD

**Issue by smartservant** [WillR27/Blocklings#15]
Hi guys. @WillR27 **I love your mod** it's the best mod ever in Minecraft by the way. :D
So now the problem. Since a few days, everybody has this problem. Whenever you go in the inventory of a blockling and click on a button you get kicked of the server with some error like: 
a fatal error has occurred or java exception.
I have installed several mods installed check the screenshot.
[https://pastebin.com/sGMqtbJg](crash server log file)
![Desktop 02-08-2019 14-55-14-786](https://user-images.githubusercontent.com/30833878/62371778-f6cc7780-b535-11e9-8084-71299c6d5855.jpg)

---Update---
So I tested it with friends and the Blocklings who they already have before the failure went up are perfectly working. Just the ones you tame now freshly are not working anymore.

**Comment by htachoires** [comment]
I have the same issue
