### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by dombu43** [WillR27/Blocklings#18]
i installed the mod and it does not work I don't see blocklings also not in the inventory

**Comment by WillR27** [comment]
Hi. Are you sure you installed the mod correctly? Did it appear in the mod list in-game? What version of Forge were you suing?

**Comment by dombu43** [comment]
hi willr27 i was using the 1.12.2 versin of forge. WillR27 <
***@***.***> schrieb am Mo. 28. März 2022 um 10:08:

**Comment by WillR27** [comment]
Ah, I see. Unfortunately, 1.12.2 is no longer supported.
