### ISSUE TITLE
Blocklings Not Spawning

### ISSUE THREAD

**Issue by DeropManz** [WillR27/Blocklings#19]
Blocklings are not Spawning in the World and i'm not fully sure whether other mods are causing the
problem but here are the mods i'm using:

1. [1.12.2]DamageIndicatorsMod-3.5.0
2. AppleSkin-Mod-1.12
3. BiomesOPlenty-1.12.2-7.0.1.2439-universal
4. Blocklings-Mod-1.12.2
5. Bookshelf-1.12.2-2.3.585
6. CoroUtil-1.12.2
7. CXLibrary-1.12.2
8. dbag-4.0
9. Enchanting-Plus-Mod-1.12.2
10. EpicSiegeMod-13.165
11. Extended-Items-Ores-Mod-1.12.2
12. foamfix-0.10.5-1.12.2
13. GalacticraftCore-1.12.2-4.0.2.229
14. Galacticraft-Planets-1.12.2-4.0.2.229
15. Giselbaers-Durability-Viewer-Mod-1.12.2
16. good-nights-sleep-1.12.2-v0.2.1
17. Grue-1.12.2-1.5.0
18. HardcoreDarkness-MC1.12.2-2.0
19. Inventory-Tweaks-Mod-1.12.2
20. jei_1.12.2-4.15.0.287 (1)
21. llibrary-1.7.19-1.12.2
22. MicdoodleCore-1.12.2-4.0.2.229
23. Mob-Battle-Mod-1.12.2
24. More-Furnaces-Mod-1.12.2
25. OptiFine_1.12.2_HD_U_E3
26. Overloaded-Armor-Bar-Mod-1.12.2
27. RoguelikeDungeons-1.12.2-1.8.0
28. somanyenchantments+V0.4.31
29. SoundFilters-0.11_for_1.12
30. Special-Mobs-Mod-1.12.2 (1)
31. Surge-1.12.2-2.0.77
32. TexFix+V-1.12-4.0
33. Tough-As-Nails-Mod-1.12.2
34. TreeCapitator-Mod-1.12 (1)
35. VanillaFix-1.0.10-99
36. VoxelMap-Mod-1.12.2
37. WIT-1.12-1.0.25-44

**Comment by WillR27** [comment]
Likelihood is that it's a Biomes o Plenty conflict. I will bear this in mind for the 1.14.4 version.

**Comment by DeropManz** [comment]
Thank You for your quick response and your correct answer. Also I love your mod.

**Comment by DeropManz** [comment]
In your latest update did you fix the Biomes O Plenty bug?
