### ISSUE TITLE
Blocklings not appearing and crash when looking for the mod in creative

### ISSUE THREAD

**Issue by dave1505** [WillR27/Blocklings#4]
Hey! So I have a big modpack and it might be related to the problem. 
Neither Blocklings nor anything related to the mod seems to appear in-game.
When searching in the creative inventory for "blockl" the game crashes immediately.

I use forge1.12.2 - 14.23.5.2768, and this is my modpack 

https://drive.google.com/open?id=1vSW12wb3-SBkX7QWwXdORn9aoq_PBvAd

Thanks and good luck! ;)

**Comment by WillR27** [comment]
Fixed.
