### ISSUE TITLE
[Enhancement] Make farming mode a right click function

### ISSUE THREAD

**Issue by edenhack** [WillR27/Blocklings#5]
Is there a way to allow the blocklings to right click harvest for farms instead of breaking the crop? This would allow support for many modded farm foods such as harvestcraft. That way you can support modded farms, without needed to somehow code the blockling to convert foods into seeds for modded food such as harvestcraft.

**Comment by WillR27** [comment]
I will have a look into this absolutely, but off the top of my head I seem to think that performing right clicks on blocks is not as easy it sounds.
