### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by larskr96** [WillR27/Blocklings#6]
**here is a list of suggestions**
1: the ability to use any kind of Axe not just Vanilla
2: a config for how far away from the log the leaves are going to break
3: min distance the blocking needs to be away from a sapling so he does not get killed
4: a way to make a blockling that is set on wander to go to a specific point after some time.
5: a config that let you blacklist Blocks that the blocking cant walk on
**And here is a question:**
are you going to make the blocking be able to use tinker's Tools?

**Comment by WillR27** [comment]
Thank you for the suggestions. I will see where I get with them and let you know. Tinker's tool integration will happen at some point, there are just other priorities at the moment.

**Comment by larskr96** [comment]
1 more thing make the blocking pick up Tools that they need for the tast they are doing
this would be good for automation of the blocklings
