### ISSUE TITLE
one more improvement

### ISSUE THREAD

**Issue by larskr96** [WillR27/Blocklings#7]
make the blocking pick up Tools that they need for the task they are doing
this would be good for automation of the blocklings

**Comment by WillR27** [comment]
Do you mean pick up off the ground?

**Comment by larskr96** [comment]
yes

**Comment by larskr96** [comment]
> Do you mean pick up off the ground?

yes

**Comment by LlubNek** [comment]
From a chest would also be nice, once you add chest interaction.
